////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace AuthorizatorService
//{
//    using System.Runtime.Serialization;
    
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
//    [System.Runtime.Serialization.DataContractAttribute(Name="NoServiceAuthorizationFault", Namespace="http://schemas.datacontract.org/2004/07/Udla.Authorization.Service.CustomExceptio" +
//        "ns")]
//    public partial class NoServiceAuthorizationFault : object
//    {
        
//        private string DescriptionField;
        
//        private string MessageField;
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string Description
//        {
//            get
//            {
//                return this.DescriptionField;
//            }
//            set
//            {
//                this.DescriptionField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string Message
//        {
//            get
//            {
//                return this.MessageField;
//            }
//            set
//            {
//                this.MessageField = value;
//            }
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
//    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/Udla.Authorization.Service.CustomExceptio" +
//        "ns")]
//    public partial class ServiceException : object
//    {
        
//        private string DescriptionField;
        
//        private string MessageField;
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string Description
//        {
//            get
//            {
//                return this.DescriptionField;
//            }
//            set
//            {
//                this.DescriptionField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string Message
//        {
//            get
//            {
//                return this.MessageField;
//            }
//            set
//            {
//                this.MessageField = value;
//            }
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
//    [System.Runtime.Serialization.DataContractAttribute(Name="NullParameterFault", Namespace="http://schemas.datacontract.org/2004/07/Udla.Authorization.Service.CustomExceptio" +
//        "ns")]
//    public partial class NullParameterFault : object
//    {
        
//        private string DescriptionField;
        
//        private string MessageField;
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string Description
//        {
//            get
//            {
//                return this.DescriptionField;
//            }
//            set
//            {
//                this.DescriptionField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string Message
//        {
//            get
//            {
//                return this.MessageField;
//            }
//            set
//            {
//                this.MessageField = value;
//            }
//        }
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
//    [System.Runtime.Serialization.DataContractAttribute(Name="SystemUserModel", Namespace="http://schemas.datacontract.org/2004/07/Udla.Authorization.Business.Models")]
//    public partial class SystemUserModel : object
//    {
        
//        private string SystemUserActiveDirectoryUserCiField;
        
//        private string SystemUserCompersEpCedulaField;
        
//        private System.DateTime SystemUserCreationDateField;
        
//        private int SystemUserCreationSystemUserIdField;
        
//        private string SystemUserDisplayNameField;
        
//        private string SystemUserEcuadorPersonNumberField;
        
//        private string SystemUserFirstFamilyNameField;
        
//        private string SystemUserFirstGivenNameField;
        
//        private string SystemUserGuidField;
        
//        private int SystemUserIdField;
        
//        private string SystemUserIntegerNumberField;
        
//        private string SystemUserNameField;
        
//        private string SystemUserOfficialNameField;
        
//        private string SystemUserOtherNumberField;
        
//        private string SystemUserSaesPersDveField;
        
//        private string SystemUserSaesPersRutpField;
        
//        private string SystemUserSaesUsuaCodiField;
        
//        private string SystemUserSecondFamilyNameField;
        
//        private string SystemUserSecondGivenNameField;
        
//        private int SystemUserValidationStatusIdField;
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string SystemUserActiveDirectoryUserCi
//        {
//            get
//            {
//                return this.SystemUserActiveDirectoryUserCiField;
//            }
//            set
//            {
//                this.SystemUserActiveDirectoryUserCiField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string SystemUserCompersEpCedula
//        {
//            get
//            {
//                return this.SystemUserCompersEpCedulaField;
//            }
//            set
//            {
//                this.SystemUserCompersEpCedulaField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public System.DateTime SystemUserCreationDate
//        {
//            get
//            {
//                return this.SystemUserCreationDateField;
//            }
//            set
//            {
//                this.SystemUserCreationDateField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public int SystemUserCreationSystemUserId
//        {
//            get
//            {
//                return this.SystemUserCreationSystemUserIdField;
//            }
//            set
//            {
//                this.SystemUserCreationSystemUserIdField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string SystemUserDisplayName
//        {
//            get
//            {
//                return this.SystemUserDisplayNameField;
//            }
//            set
//            {
//                this.SystemUserDisplayNameField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string SystemUserEcuadorPersonNumber
//        {
//            get
//            {
//                return this.SystemUserEcuadorPersonNumberField;
//            }
//            set
//            {
//                this.SystemUserEcuadorPersonNumberField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string SystemUserFirstFamilyName
//        {
//            get
//            {
//                return this.SystemUserFirstFamilyNameField;
//            }
//            set
//            {
//                this.SystemUserFirstFamilyNameField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string SystemUserFirstGivenName
//        {
//            get
//            {
//                return this.SystemUserFirstGivenNameField;
//            }
//            set
//            {
//                this.SystemUserFirstGivenNameField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string SystemUserGuid
//        {
//            get
//            {
//                return this.SystemUserGuidField;
//            }
//            set
//            {
//                this.SystemUserGuidField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public int SystemUserId
//        {
//            get
//            {
//                return this.SystemUserIdField;
//            }
//            set
//            {
//                this.SystemUserIdField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string SystemUserIntegerNumber
//        {
//            get
//            {
//                return this.SystemUserIntegerNumberField;
//            }
//            set
//            {
//                this.SystemUserIntegerNumberField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string SystemUserName
//        {
//            get
//            {
//                return this.SystemUserNameField;
//            }
//            set
//            {
//                this.SystemUserNameField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string SystemUserOfficialName
//        {
//            get
//            {
//                return this.SystemUserOfficialNameField;
//            }
//            set
//            {
//                this.SystemUserOfficialNameField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string SystemUserOtherNumber
//        {
//            get
//            {
//                return this.SystemUserOtherNumberField;
//            }
//            set
//            {
//                this.SystemUserOtherNumberField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string SystemUserSaesPersDve
//        {
//            get
//            {
//                return this.SystemUserSaesPersDveField;
//            }
//            set
//            {
//                this.SystemUserSaesPersDveField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string SystemUserSaesPersRutp
//        {
//            get
//            {
//                return this.SystemUserSaesPersRutpField;
//            }
//            set
//            {
//                this.SystemUserSaesPersRutpField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string SystemUserSaesUsuaCodi
//        {
//            get
//            {
//                return this.SystemUserSaesUsuaCodiField;
//            }
//            set
//            {
//                this.SystemUserSaesUsuaCodiField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string SystemUserSecondFamilyName
//        {
//            get
//            {
//                return this.SystemUserSecondFamilyNameField;
//            }
//            set
//            {
//                this.SystemUserSecondFamilyNameField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public string SystemUserSecondGivenName
//        {
//            get
//            {
//                return this.SystemUserSecondGivenNameField;
//            }
//            set
//            {
//                this.SystemUserSecondGivenNameField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public int SystemUserValidationStatusId
//        {
//            get
//            {
//                return this.SystemUserValidationStatusIdField;
//            }
//            set
//            {
//                this.SystemUserValidationStatusIdField = value;
//            }
//        }
//    }
    
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
//    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthorizatorService.IAuthorizatorService")]
//    public interface IAuthorizatorService
//    {
        
//        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizatorService/IsAuthorized", ReplyAction="http://tempuri.org/IAuthorizatorService/IsAuthorizedResponse")]
//        [System.ServiceModel.FaultContractAttribute(typeof(AuthorizatorService.NoServiceAuthorizationFault), Action="http://tempuri.org/IAuthorizatorService/IsAuthorizedNoServiceAuthorizationFaultFa" +
//            "ult", Name="NoServiceAuthorizationFault", Namespace="http://schemas.datacontract.org/2004/07/Udla.Authorization.Service.CustomExceptio" +
//            "ns")]
//        [System.ServiceModel.FaultContractAttribute(typeof(AuthorizatorService.ServiceException), Action="http://tempuri.org/IAuthorizatorService/IsAuthorizedServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/Udla.Authorization.Service.CustomExceptio" +
//            "ns")]
//        [System.ServiceModel.FaultContractAttribute(typeof(AuthorizatorService.NullParameterFault), Action="http://tempuri.org/IAuthorizatorService/IsAuthorizedNullParameterFaultFault", Name="NullParameterFault", Namespace="http://schemas.datacontract.org/2004/07/Udla.Authorization.Service.CustomExceptio" +
//            "ns")]
//        System.Threading.Tasks.Task<bool> IsAuthorizedAsync(string systemUserName, string systemApplicationCode, string systemPermissionCode, string securityToken);
        
//        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizatorService/HasAnyAuthorization", ReplyAction="http://tempuri.org/IAuthorizatorService/HasAnyAuthorizationResponse")]
//        [System.ServiceModel.FaultContractAttribute(typeof(AuthorizatorService.NoServiceAuthorizationFault), Action="http://tempuri.org/IAuthorizatorService/HasAnyAuthorizationNoServiceAuthorization" +
//            "FaultFault", Name="NoServiceAuthorizationFault", Namespace="http://schemas.datacontract.org/2004/07/Udla.Authorization.Service.CustomExceptio" +
//            "ns")]
//        [System.ServiceModel.FaultContractAttribute(typeof(AuthorizatorService.ServiceException), Action="http://tempuri.org/IAuthorizatorService/HasAnyAuthorizationServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/Udla.Authorization.Service.CustomExceptio" +
//            "ns")]
//        [System.ServiceModel.FaultContractAttribute(typeof(AuthorizatorService.NullParameterFault), Action="http://tempuri.org/IAuthorizatorService/HasAnyAuthorizationNullParameterFaultFaul" +
//            "t", Name="NullParameterFault", Namespace="http://schemas.datacontract.org/2004/07/Udla.Authorization.Service.CustomExceptio" +
//            "ns")]
//        System.Threading.Tasks.Task<bool> HasAnyAuthorizationAsync(string systemUserName, string systemApplicationCode, string securityToken);
        
//        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizatorService/GetSystemUser", ReplyAction="http://tempuri.org/IAuthorizatorService/GetSystemUserResponse")]
//        [System.ServiceModel.FaultContractAttribute(typeof(AuthorizatorService.NoServiceAuthorizationFault), Action="http://tempuri.org/IAuthorizatorService/GetSystemUserNoServiceAuthorizationFaultF" +
//            "ault", Name="NoServiceAuthorizationFault", Namespace="http://schemas.datacontract.org/2004/07/Udla.Authorization.Service.CustomExceptio" +
//            "ns")]
//        [System.ServiceModel.FaultContractAttribute(typeof(AuthorizatorService.ServiceException), Action="http://tempuri.org/IAuthorizatorService/GetSystemUserServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/Udla.Authorization.Service.CustomExceptio" +
//            "ns")]
//        [System.ServiceModel.FaultContractAttribute(typeof(AuthorizatorService.NullParameterFault), Action="http://tempuri.org/IAuthorizatorService/GetSystemUserNullParameterFaultFault", Name="NullParameterFault", Namespace="http://schemas.datacontract.org/2004/07/Udla.Authorization.Service.CustomExceptio" +
//            "ns")]
//        System.Threading.Tasks.Task<AuthorizatorService.SystemUserModel> GetSystemUserAsync(string systemUserName, string securityToken);
        
//        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizatorService/GetSystemUserByIdentificacion", ReplyAction="http://tempuri.org/IAuthorizatorService/GetSystemUserByIdentificacionResponse")]
//        [System.ServiceModel.FaultContractAttribute(typeof(AuthorizatorService.NoServiceAuthorizationFault), Action="http://tempuri.org/IAuthorizatorService/GetSystemUserByIdentificacionNoServiceAut" +
//            "horizationFaultFault", Name="NoServiceAuthorizationFault", Namespace="http://schemas.datacontract.org/2004/07/Udla.Authorization.Service.CustomExceptio" +
//            "ns")]
//        [System.ServiceModel.FaultContractAttribute(typeof(AuthorizatorService.ServiceException), Action="http://tempuri.org/IAuthorizatorService/GetSystemUserByIdentificacionServiceExcep" +
//            "tionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/Udla.Authorization.Service.CustomExceptio" +
//            "ns")]
//        [System.ServiceModel.FaultContractAttribute(typeof(AuthorizatorService.NullParameterFault), Action="http://tempuri.org/IAuthorizatorService/GetSystemUserByIdentificacionNullParamete" +
//            "rFaultFault", Name="NullParameterFault", Namespace="http://schemas.datacontract.org/2004/07/Udla.Authorization.Service.CustomExceptio" +
//            "ns")]
//        System.Threading.Tasks.Task<AuthorizatorService.SystemUserModel> GetSystemUserByIdentificacionAsync(string identificacion, string securityToken);
//    }
    
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
//    public interface IAuthorizatorServiceChannel : AuthorizatorService.IAuthorizatorService, System.ServiceModel.IClientChannel
//    {
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
//    public partial class AuthorizatorServiceClient : System.ServiceModel.ClientBase<AuthorizatorService.IAuthorizatorService>, AuthorizatorService.IAuthorizatorService
//    {
        
//        /// <summary>
//        /// Implement this partial method to configure the service endpoint.
//        /// </summary>
//        /// <param name="serviceEndpoint">The endpoint to configure</param>
//        /// <param name="clientCredentials">The client credentials</param>
//        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
//        public AuthorizatorServiceClient() : 
//                base(AuthorizatorServiceClient.GetDefaultBinding(), AuthorizatorServiceClient.GetDefaultEndpointAddress())
//        {
//            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAuthorizatorService.ToString();
//            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
//        }
        
//        public AuthorizatorServiceClient(EndpointConfiguration endpointConfiguration) : 
//                base(AuthorizatorServiceClient.GetBindingForEndpoint(endpointConfiguration), AuthorizatorServiceClient.GetEndpointAddress(endpointConfiguration))
//        {
//            this.Endpoint.Name = endpointConfiguration.ToString();
//            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
//        }
        
//        public AuthorizatorServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
//                base(AuthorizatorServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
//        {
//            this.Endpoint.Name = endpointConfiguration.ToString();
//            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
//        }
        
//        public AuthorizatorServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
//                base(AuthorizatorServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
//        {
//            this.Endpoint.Name = endpointConfiguration.ToString();
//            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
//        }
        
//        public AuthorizatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
//                base(binding, remoteAddress)
//        {
//        }
        
//        public System.Threading.Tasks.Task<bool> IsAuthorizedAsync(string systemUserName, string systemApplicationCode, string systemPermissionCode, string securityToken)
//        {
//            return base.Channel.IsAuthorizedAsync(systemUserName, systemApplicationCode, systemPermissionCode, securityToken);
//        }
        
//        public System.Threading.Tasks.Task<bool> HasAnyAuthorizationAsync(string systemUserName, string systemApplicationCode, string securityToken)
//        {
//            return base.Channel.HasAnyAuthorizationAsync(systemUserName, systemApplicationCode, securityToken);
//        }
        
//        public System.Threading.Tasks.Task<AuthorizatorService.SystemUserModel> GetSystemUserAsync(string systemUserName, string securityToken)
//        {
//            return base.Channel.GetSystemUserAsync(systemUserName, securityToken);
//        }
        
//        public System.Threading.Tasks.Task<AuthorizatorService.SystemUserModel> GetSystemUserByIdentificacionAsync(string identificacion, string securityToken)
//        {
//            return base.Channel.GetSystemUserByIdentificacionAsync(identificacion, securityToken);
//        }
        
//        public virtual System.Threading.Tasks.Task OpenAsync()
//        {
//            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
//        }
        
//        public virtual System.Threading.Tasks.Task CloseAsync()
//        {
//            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
//        }
        
//        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
//        {
//            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuthorizatorService))
//            {
//                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
//                result.MaxBufferSize = int.MaxValue;
//                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
//                result.MaxReceivedMessageSize = int.MaxValue;
//                result.AllowCookies = true;
//                return result;
//            }
//            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
//        }
        
//        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
//        {
//            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuthorizatorService))
//            {
//                return new System.ServiceModel.EndpointAddress("http://10.190.0.42/AuthorizatorService.svc");
//            }
//            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
//        }
        
//        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
//        {
//            return AuthorizatorServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAuthorizatorService);
//        }
        
//        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
//        {
//            return AuthorizatorServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAuthorizatorService);
//        }
        
//        public enum EndpointConfiguration
//        {
            
//            BasicHttpBinding_IAuthorizatorService,
//        }
//    }
//}
